### ISSUE TITLE
Docker Service Discrepancy on Windows v. Linux host

### ISSUE THREAD

**Issue by nfadeluca** [ava-labs/avalanche-cli#1405]
When running avax-cli container on Windows, there are no issues, CLI runs normally in/out of container.
When running on either an Ubuntu-VM or Fedora OS, error appears:
`Error: failed to start network :rpc error: code = Unknown desc = node "node2" stopped unexpectedly`

Relevant parts of docker-compose:

```
avalanche:
    build:
      context: .
      dockerfile: DockerfileAvaxCli
    ports:
     - "9650:9650"
    expose:
      - '9650'
    networks:
      - ip6net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB9::/111
```

DockerAvaxCli file:
```
# Use Ubuntu 20.04 as the base image
FROM ubuntu:20.04 as avalanche-cli

# Set a non-interactive frontend for apt-get to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install dependencies in a single RUN command to reduce layers
RUN apt-get update && \
    apt-get install -y \
    tzdata \
    curl \
    python3 \
    python3-pip \
    expect \
    dos2unix && \
    # Clean up to reduce image size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python pexpect package
RUN pip3 install pexpect

# Download and install the Avalanche-CLI binary
RUN curl -sSfL https://raw.githubusercontent.com/ava-labs/avalanche-cli/main/scripts/install.sh | sh -s -- -b /usr/local/bin

# Set the working directory
WORKDIR /

# Copy the entrypoint script and the Avalanche CLI configuration file into the container
COPY ./docker_entrypoints/avax-entrypoint.sh /avax-entrypoint.sh
COPY ./config/avax_cli_config.json /avaxconfig/config.json

# Convert line endings to Unix format and make the script executable
RUN dos2unix /avax-entrypoint.sh && \
    chmod +x /avax-entrypoint.sh

# Set the entrypoint script to be executed when the container starts
ENTRYPOINT ["/avax-entrypoint.sh"]
```

This problem didn't always occur, it worked in Linux environment a little while ago, probably around a couple months or so (sometimes similar errors would appear, but restart would usually fix).
However, now this error always appears.
